### ISSUE TITLE
current status of web liquid streams?

### ISSUE THREAD

**Issue by edwmurph** [masiarb/Web-Liquid-Streams#1]
i'm a javascript developer looking to build a distributed data pipeline and this seems to be the closest javascript native solution.

is this project still being developed? if not, could you recommend another tool for building distributed data pipelines in javascript?

**Comment by masiarb** [comment]
Hi, the development of WLS has been terminated as my PhD thesis ended :). I cannot really help with suggesting tools to build distributed data pipelines in JavaScript - at the time of my thesis WLS was the only tool around to build such data streaming pipelines in JS and being as flexible. 

You are free and welcome to look at the code, spot all the bad code design choices I've taken, and why not, try to play around with it a little bit. Building the project is a bit tedious as far as I can remember, once that's done it's fun to play around with it heh.

**Comment by edwmurph** [comment]
no problem thanks!
